# Generated by Django 5.2.1 on 2025-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_materia_docente_grupomateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
