# Generated by Django 5.2.1 on 2025-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_grupo_is_active_materia_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grado',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
    ]
