# Generated by Django 5.2.1 on 2025-08-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_grupo_grado 2'),
        ('gestion', '0005_alter_grupo_grado'),
    ]

    operations = [
    ]
