# Generated by Django 5.2.1 on 2025-08-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_merge_0005_alter_grupo_grado_0005_alter_grupo_grado 2'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomateria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
