# Generated by Django 5.2.1 on 2025-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_grupomateria_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("materia", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="docente",
            name="especialidad",
        ),
        migrations.AddField(
            model_name="docente",
            name="especialidades",
            field=models.ManyToManyField(to="gestion.especialidad"),
        ),
    ]
