# Generated by Django 5.2.1 on 2025-09-21 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_especialidad_remove_docente_especialidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cedula',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='gestion.especialidad'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='materia',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
